name: 'GitHub Actions Slack Notify'
description: 'Send notifications to Slack'
author: 'Duc Duong <duc.duong@c0x12c.com>'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  num-commits:
    description: 'The number of recent commis included in the message'
    required: false
    default: '3'
  project_url:
    description: 'The project URL for preview'
    required: false
  title:
    description: 'The message title'
    required: true
  webhook_url:
    description: 'The Slack webhook URL'
    required: true

runs:
  using: node20
  main: dist/index.js
